### ISSUE TITLE
Allow references for responses

### ISSUE THREAD

**Issue by ArthurWD** [westfieldlabs/apivore#84]
I would like to be able to reuse responses by setting references, like this:
```
"paths": {
  "/path.json": {
    "get": {
      "resource": {
        "401": {
          "$ref": "#/responses/NotLoggedIn"
        }
      }
    }
  },
"responses": {
  "NotLoggedIn": {
    "schema": {
      "$ref": "#/definitions/Error"
    }
  }
```

Currently, it ignores the reference, letting any value pass. My current attempt is to fix this is by altering Apivore::Swagger.each_response:
```
method_data.responses.each do |response_code, response_data|
  schema_location = nil
  if response_data.schema
    schema_location = Fragment.new ['#', 'paths', path, verb, 'responses', response_code, 'schema']
  elsif response_data.send(:$ref)
    schema_location = Fragment.new response_data.send(:$ref).split('/').push('schema')
  end
  block.call(path, verb, response_code, schema_location)
end
```

But this raises "NoMethodError: undefined method `validate' for {"$ref"=>"#/definitions/Error"}:Hash"

- /.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/json-schema-2.6.1/lib/json-schema/validator.rb:114:in `validate'
- /.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/json-schema-2.6.1/lib/json-schema/validator.rb:276:in `fully_validate'
- /.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/apivore-1.6.0/lib/apivore/swagger_checker.rb:26:in `has_matching_document_for'
- /.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/apivore-1.6.0/lib/apivore/validator.rb:95:in `check_response_is_valid'
- /.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/apivore-1.6.0/lib/apivore/validator.rb:65:in `post_checks'
- /.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/apivore-1.6.0/lib/apivore/validator.rb:28:in `matches?'
- ./spec/requests/api_spec.rb:18:in 'block (3 levels) in <top (required)>'

Any plans for supporting this?

**Comment by ashoda** [comment]
@gwshaw @jreece1567 this seems pretty reasonable. Any reservations about supporting this?

If we're in agreement about supporting this, there is an outstanding PR that we should review and get moving. https://github.com/westfieldlabs/apivore/pull/89

**Comment by jreece1567** [comment]
I'm fine with supporting this. We *must not* use this capability in our internal westfield swagger, but Apivore should support it as it is part of the public swagger-specification.

cc: @ashoda @gwshaw

**Comment by lucasrenan** [comment]
looks like it's more `json-schema` gem limitation than `apivore`. when using fragments, `json-schema` seems not being able to understand the `$ref`:

https://github.com/ruby-json-schema/json-schema/blob/master/lib/json-schema/validator.rb#L85

anyways, https://github.com/westfieldlabs/apivore/pull/89 should fix it.

**Comment by Deuteu** [comment]
@ashoda Any update about this issue ?
